config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  resources :users do
    resources :goals, only: [:new, :index]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:new, :index]
  resources :goal_comments, only: [:create, :destroy]
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  privacy     :boolean          default(FALSE), not null
#  completion  :boolean          default(FALSE), not null
#

class Goal < ActiveRecord::Base
  validates :title, :description, :user, presence: true
  validates :privacy, :completion, inclusion: { in: [true, false, nil] }
  
  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many(
    :comments,
    class_name: "GoalComment",
    foreign_key: :goal_id,
    primary_key: :id
  )
end

app/models/goal_comment.rb
# == Schema Information
#
# Table name: goal_comments
#
#  id         :integer          not null, primary key
#  author_id  :integer          not null
#  goal_id    :integer          not null
#  body       :text             not null
#  created_at :datetime
#  updated_at :datetime
#

class GoalComment < ActiveRecord::Base
  validates :author, :goal, :body, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  belongs_to(
    :goal,
    class_name: "Goal",
    foreign_key: :goal_id,
    primary_key: :id,
    inverse_of: :comments
  )
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  
  has_many :goals
  has_many(
    :goal_comments,
    class_name: "GoalComment",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(user_credentials)
    user = User.find_by_username(user_credentials[:username])
    user && user.is_password?(user_credentials[:password]) ? user : nil
  end
end

app/models/user_comment.rb
# == Schema Information
#
# Table name: user_comments
#
#  id         :integer          not null, primary key
#  subject_id :integer          not null
#  author_id  :integer          not null
#  body       :text             not null
#  created_at :datetime
#  updated_at :datetime
#

class UserComment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user
  
  def log_in!
    session[:session_token] = @user.reset_session_token!
  end
  
  def logged_in?
    !!current_user
  end
  
  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
  def require_sign_in
    redirect_to new_session_url unless logged_in?
  end
  
  def require_user_to_own_goal
    unless Goal.find(params[:id]).user_id == current_user.id
      redirect_to user_goals_url(current_user) 
    end
  end
end

app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController
  def create
    @comment = GoalComment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    redirect_to goal_url(@comment.goal)
  end
  
  def destroy
    @comment = GoalComment.find(params[:id])
    @comment.destroy
    redirect_to goal_url(@comment.goal)
  end
  
  def comment_params
    params.require(:comment).permit(:body, :goal_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_sign_in
  before_action :require_user_to_own_goal, only: [:edit, :update, :destroy]
  
  def new
    @user = User.find(params[:user_id])
    @goal = Goal.new
  end
  
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def show
    @goal = Goal.find(params[:id])
  end
  
  def index
    @goals = Goal.where('user_id = ?', params[:user_id])
  end
  
  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url(current_user)
  end
  
  def edit
    @goal = Goal.find(params[:id])
  end
  
  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def goal_params
    params.require(:goal).permit(:title, :description, :completion)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_credentials(user_params)
    if @user
      log_in!
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in!
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def index
  end
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\"
           name=\"authenticity_token\"
           value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
 <% if @goal.persisted? %>
   <% action = goal_url(@goal) %>
   <% button_text = "Update Goal" %>
   <% method = "PATCH" %>
 <% else %>
   <% action = goals_url %>
   <% button_text = "Set Goal!" %>
   <% method = "POST" %>
 <% end %>

<form action="<%= action %>" method="POST">
  <%= auth_token %>
   <input type="hidden" name="_method" value="<%= method %>">
  <label>Goal
    <input type="text" 
           name="goal[title]" 
           value="<%= @goal.title %>">
  </label>
  
  <label>Description
    <textarea name="goal[description]"><%= @goal.description %></textarea>
  </label>
  
   <% if @goal.persisted? %>
     <label>Goal Complete!
       <input type="radio" 
              name="goal[completion]" 
              value="true"
              <%= "checked" if @goal.completion %>>
     </label>
     <label>Goal in Progress!
       <input type="radio" 
              name="goal[completion]" 
              value="false"
              <%= "checked" if !@goal.completion %>>
     </label>
   <% end %>
  
  <input type="submit" value="<%= button_text %>">
</form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render 'form' %>

app/views/goals/index.html.erb
<% @goals.each do |goal| %>
  <% if goal.user_id == current_user.id || goal.privacy == false %>
    <%= link_to goal.title, goal_url(goal) %>
  <% end %>
<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>
<form action="<%= goals_url %>" method="POST">
  <%= auth_token %>
  <label>Goal
    <input type="text" 
           name="goal[title]" 
           value="<%= @goal.title %>">
  </label>
  
  <label>Description
    <textarea name="goal[description]"><%= @goal.description %></textarea>
  </label>
  
  <input type="submit" value="Set Goal!">
</form>

app/views/goals/show.html.erb
<% if @goal.user_id != current_user.id && @goal.privacy %>

<p>This goal is private</p>

<% else %>

<h1><%= @goal.title %></h1>

<p><%= @goal.description %></p>

  <% if @goal.completion %>
    <%= "Goal Completed!" %>
  <% else %>
    <%= "Goal in Progress!" %>
  <% end %>
  
<% end %>

<% if current_user.id == @goal.id %>
  <%= link_to "Update Goal", edit_goal_url(@goal) %>
  <%= button_to "Remove Goal", goal_url(@goal), method: :delete %>
<% end %>

<% @goal.comments.each do |comment| %>
  <%= comment.body %>
   <%= button_to "Remove Comment", goal_comment_url(comment), method: :delete %>
<% end %>

<form action="<%= goal_comments_url %>" method="POST">
  <%= auth_token %>
  <label>Comment
    <textarea name="comment[body]"></textarea>
  </label>
  
  <input type="hidden" name="comment[goal_id]" value="<%= @goal.id %>">
  
  <input type="submit" value="Add Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% if flash[:errors] %>
  <%= flash[:errors].join("<br>").html_safe %>
<% end %>


<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <label>Username
    <input type="text" name="user[username]">
  </label>
  
  <label>Password
    <input type="password" name="user[password]">
  </label>
  
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<% @user.comments.each do |comment| %>

<% end %>